#ifndef SIGNALSLINGER_BOOTLOADER_CONFIG_H
#define SIGNALSLINGER_BOOTLOADER_CONFIG_H

#include <stdint.h>

#ifndef F_CPU
#define F_CPU 24000000UL
#endif

#define SIGNALSLINGER_BOOTLOADER_VERSION "BL0.11"
#define SIGNALSLINGER_BOOT_PROTOCOL_VERSION 1U
#define SIGNALSLINGER_BOOT_SECTION_PAGES 32U
#define SIGNALSLINGER_FLASH_PAGE_BYTES 512U
#define SIGNALSLINGER_FLASH_BYTES 131072UL
#define SIGNALSLINGER_APP_START_BYTES (SIGNALSLINGER_BOOT_SECTION_PAGES * SIGNALSLINGER_FLASH_PAGE_BYTES)
#define SIGNALSLINGER_APP_START_WORDS (SIGNALSLINGER_APP_START_BYTES / 2U)

#define SIGNALSLINGER_BOOT_USART_BAUD 115200UL
#define SIGNALSLINGER_BOOT_ENTRY_WINDOW_MS 1500U

#define SIGNALSLINGER_UPDATE_REQUEST_CHAR 'U'
#define SIGNALSLINGER_RUN_APP_CHAR 'R'
#define SIGNALSLINGER_INFO_CHAR '?'
#define SIGNALSLINGER_ERASE_PAGE_CHAR 'E'
#define SIGNALSLINGER_WRITE_PAGE_CHAR 'W'
#define SIGNALSLINGER_CRC_PAGE_CHAR 'C'

#define SIGNALSLINGER_BOOT_FRAME_BYTE_TIMEOUT_MS 1000U

static_assert(SIGNALSLINGER_APP_START_BYTES == 0x4000U, "Unexpected bootloader application start");
static_assert((SIGNALSLINGER_APP_START_BYTES % SIGNALSLINGER_FLASH_PAGE_BYTES) == 0U, "App start must be page aligned");

#endif /* SIGNALSLINGER_BOOTLOADER_CONFIG_H */
