M48
; DRILL file {KiCad 8.0.9} date 2025-09-12T08:00:09-0400
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-09-12T08:00:09-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.9
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0295
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0787
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.1378
%
G90
G05
T1
X3.2358Y-4.5203
X3.2358Y-4.6285
T2
X2.8524Y-2.4606
X2.9945Y-2.4606
X4.5386Y-2.4984
T3
X4.1567Y-3.1929
M30
