/**
 * \file
 *
 * \brief Driver ISR.
 *
 (c) 2020 Microchip Technology Inc. and its subsidiaries.

    Subject to your compliance with these terms,you may use this software and
    any derivatives exclusively with Microchip products.It is your responsibility
    to comply with third party license terms applicable to your use of third party
    software (including open source software) that may accompany Microchip software.

    THIS SOFTWARE IS SUPPLIED BY MICROCHIP "AS IS". NO WARRANTIES, WHETHER
    EXPRESS, IMPLIED OR STATUTORY, APPLY TO THIS SOFTWARE, INCLUDING ANY IMPLIED
    WARRANTIES OF NON-INFRINGEMENT, MERCHANTABILITY, AND FITNESS FOR A
    PARTICULAR PURPOSE.

    IN NO EVENT WILL MICROCHIP BE LIABLE FOR ANY INDIRECT, SPECIAL, PUNITIVE,
    INCIDENTAL OR CONSEQUENTIAL LOSS, DAMAGE, COST OR EXPENSE OF ANY KIND
    WHATSOEVER RELATED TO THE SOFTWARE, HOWEVER CAUSED, EVEN IF MICROCHIP HAS
    BEEN ADVISED OF THE POSSIBILITY OR THE DAMAGES ARE FORESEEABLE. TO THE
    FULLEST EXTENT ALLOWED BY LAW, MICROCHIP'S TOTAL LIABILITY ON ALL CLAIMS IN
    ANY WAY RELATED TO THIS SOFTWARE WILL NOT EXCEED THE AMOUNT OF FEES, IF ANY,
    THAT YOU HAVE PAID DIRECTLY TO MICROCHIP FOR THIS SOFTWARE.
 *
 */

/*
 * Code generated by START.
 *
 * This file will be overwritten when reconfiguring your START project.
 * Please copy examples or other code you want to keep to a separate file
 * to avoid losing it when reconfiguring.
 */

#include <driver_init.h>
#include <compiler.h>
#include <atomic.h>
#include <ctype.h> /* toupper() */
#include <string.h>
#include "serialbus.h"
#include "usart_basic.h"
#include "morse.h"
#include "globals.h"

void serial_Rx(uint8_t rx_char);
static int serialbus_parse_msg_id(const char *text, uint8_t len);

#define SERIALBUS_MAX_ESC_SEQUENCE_LENGTH 16
#define SERIALBUS_RX_IDLE_TIMEOUT_HUMAN_MS 8000U
#define SERIALBUS_RX_IDLE_TIMEOUT_NOISE_MS 500U

static char g_serial_rx_textBuff[SERIALBUS_MAX_MSG_LENGTH];
static SerialbusRxBuffer *g_serial_rx_buff = NULL;
static uint8_t g_serial_rx_charIndex = 0;
static uint8_t g_serial_rx_field_index = 0;
static uint8_t g_serial_rx_field_len = 0;
static int g_serial_rx_msg_ID = SB_MESSAGE_EMPTY;
static uint8_t g_serial_rx_escapeCount = 0;
static volatile uint16_t g_serial_rx_idle_ticks = 0;
static bool g_serial_rx_receiving_msg = false;
static bool g_serial_rx_ignoreAllInput = false;
static bool g_serial_rx_inEscapeSequence = false;
static volatile bool g_serial_rx_useMeshMode = false;
static bool g_serial_rx_invalidCommand = false;

static void serial_rx_idle_ticks_write_atomic(uint16_t value)
{
	ENTER_CRITICAL(serial_rx_idle_ticks_write);
	g_serial_rx_idle_ticks = value;
	EXIT_CRITICAL(serial_rx_idle_ticks_write);
}

static uint16_t serialbus_rx_idle_reload_ticks(void)
{
	if(g_serial_rx_invalidCommand || g_serial_rx_inEscapeSequence || g_serial_rx_ignoreAllInput)
	{
		return SERIALBUS_RX_IDLE_TIMEOUT_NOISE_MS;
	}

	if(g_serial_rx_receiving_msg || g_serial_rx_charIndex)
	{
		return SERIALBUS_RX_IDLE_TIMEOUT_HUMAN_MS;
	}

	return 0;
}

static int serialbus_parse_msg_id(const char *text, uint8_t len)
{
	int msg_id = SB_MESSAGE_EMPTY;

	for(uint8_t i = 0; i < len; i++)
	{
		msg_id = (i == 0) ? text[i] : (msg_id * 10 + text[i]);
	}

	return msg_id;
}

void serialbus_reset_rx_parser(void)
{
	memset(g_serial_rx_textBuff, 0, sizeof(g_serial_rx_textBuff));
	g_serial_rx_buff = NULL;
	g_serial_rx_charIndex = 0;
	g_serial_rx_field_index = 0;
	g_serial_rx_field_len = 0;
	g_serial_rx_msg_ID = SB_MESSAGE_EMPTY;
	g_serial_rx_escapeCount = 0;
	serial_rx_idle_ticks_write_atomic(0);
	g_serial_rx_receiving_msg = false;
	g_serial_rx_ignoreAllInput = false;
	g_serial_rx_inEscapeSequence = false;
	g_serial_rx_invalidCommand = false;
}

void serialbus_set_rx_mesh_mode(bool enabled)
{
	g_serial_rx_useMeshMode = enabled;
}

void serialbus_rx_idle_tick(void)
{
	if(g_serial_rx_idle_ticks)
	{
		g_serial_rx_idle_ticks--;
		if(!g_serial_rx_idle_ticks)
		{
			if(g_serial_rx_buff && !g_serial_rx_useMeshMode)
			{
				g_serial_rx_buff->type = SERIALBUS_MSG_INVALID;
				g_serial_rx_buff->id = SB_RX_IDLE_TIMEOUT;
			}

			serialbus_reset_rx_parser();
		}
	}
}

ISR(USART0_RXC_vect)
{
	uint8_t rx_char = USART0_get_data();

	if(g_serialbus_usart_number == USART_0)
	{
		serial_Rx(rx_char);
	}
}

// void __attribute__((optimize("O0"))) serial_Rx(uint8_t rx_char)
void serial_Rx(uint8_t rx_char)
{
	uint8_t echo_char = rx_char;

	if(!g_serial_rx_buff)
	{
		g_serial_rx_buff = nextEmptySBRxBuffer();
	}

	if(g_serial_rx_buff)
	{
		serial_rx_idle_ticks_write_atomic(serialbus_rx_idle_reload_ticks());

		if(rx_char == 0x08)
		{
			rx_char = 0x7F;
		}
		else
		{
			rx_char = toupper(rx_char);
			echo_char = rx_char;
		}
		if(rx_char == '\n')
			rx_char = '\r';

		if(g_serial_rx_ignoreAllInput)
		{
			if(rx_char == '\r') /* Handle carriage return */
			{
				g_serial_rx_ignoreAllInput = false;
			}

			rx_char = '\0';
		}
		else if(g_serial_rx_inEscapeSequence)
		{
			g_serial_rx_escapeCount++;
			rx_char = '\0';

			if(g_serial_rx_escapeCount == 1U)
			{
				if((echo_char != '[') && (echo_char != 'O'))
				{
					g_serial_rx_inEscapeSequence = false;
				}
			}
			else if((echo_char == '\r') ||
			        ((echo_char >= 0x40U) && (echo_char <= 0x7EU)) ||
			        (g_serial_rx_escapeCount >= SERIALBUS_MAX_ESC_SEQUENCE_LENGTH))
			{
				g_serial_rx_inEscapeSequence = false;
			}
		}
		else if(rx_char == 0x1B) /* Ignore ESC sequences */
		{
			rx_char = '\0';
			g_serial_rx_inEscapeSequence = true;
			g_serial_rx_escapeCount = 0;
		}
		else if(rx_char == '*') /* Ignore all input until a carriage return is received */
		{
			g_serial_rx_ignoreAllInput = true;
			rx_char = '\0';
		}
		else if(rx_char == '\r') /* Handle carriage return */
		{
			SBMessageID completed_id = SB_MESSAGE_EMPTY;
			bool publish_msg = false;

			if(g_serial_rx_receiving_msg)
			{
				if(g_serial_rx_charIndex > 0)
				{
					g_serial_rx_buff->type = SERIALBUS_MSG_QUERY;

					if((g_serial_rx_charIndex == 1) && (g_serial_rx_textBuff[0] == '?'))
					{
						completed_id = g_serial_rx_useMeshMode ? SB_MESSAGE_EMPTY : SB_MESSAGE_HELP;
						publish_msg = true;
					}
					else if(g_serial_rx_invalidCommand)
					{
						completed_id = g_serial_rx_useMeshMode ? SB_MESSAGE_EMPTY : SB_INVALID_MESSAGE;
						publish_msg = true;
					}
					else
					{
						if(g_serial_rx_field_index > 0) /* terminate the last field */
						{
							g_serial_rx_buff->fields[g_serial_rx_field_index - 1][g_serial_rx_field_len] = 0;
						}

						g_serial_rx_textBuff[g_serial_rx_charIndex] = '\0'; /* terminate last-message buffer */
						completed_id = (SBMessageID)g_serial_rx_msg_ID;
						publish_msg = true;
					}
				}
			}
			else
			{
				completed_id = SB_CR_NO_DATA; /* handle blank line */
				publish_msg = true;
			}

			if(publish_msg)
			{
				/* Publish last so foreground sees a fully-populated message buffer. */
				g_serial_rx_buff->id = completed_id;
			}

			serialbus_reset_rx_parser();
		}
		else if(rx_char)
		{
			g_serial_rx_textBuff[g_serial_rx_charIndex] = rx_char; /* hold the characters for re-use */

			if(g_serial_rx_charIndex)
			{
				if(rx_char == 0x7F) /* Handle backspace */
				{
					g_serial_rx_charIndex--;

					if(g_serial_rx_field_index == 0)
					{
						if(g_serial_rx_field_len)
						{
							g_serial_rx_field_len--;
						}

						g_serial_rx_textBuff[g_serial_rx_charIndex] = '\0'; /* replace deleted char with null */
						g_serial_rx_invalidCommand = (g_serial_rx_field_len > SERIALBUS_MAX_MSG_ID_LENGTH);
						g_serial_rx_msg_ID = (!g_serial_rx_invalidCommand && g_serial_rx_field_len)
						                         ? serialbus_parse_msg_id(g_serial_rx_textBuff, g_serial_rx_field_len)
						                         : SB_MESSAGE_EMPTY;
					}
					else if(g_serial_rx_field_len)
					{
						g_serial_rx_field_len--;
						g_serial_rx_buff->fields[g_serial_rx_field_index - 1][g_serial_rx_field_len] = '\0';
						g_serial_rx_textBuff[g_serial_rx_charIndex] = '\0'; /* replace deleted char with null */
					}
					else if(g_serial_rx_textBuff[g_serial_rx_charIndex] == ' ')
					{
						g_serial_rx_field_index--;
						g_serial_rx_field_len = strlen(g_serial_rx_buff->fields[g_serial_rx_field_index]);
						g_serial_rx_textBuff[g_serial_rx_charIndex] = '\0'; /* replace deleted char with null */
					}
					else
					{
						g_serial_rx_buff->fields[g_serial_rx_field_index][0] = '\0';
						g_serial_rx_field_index--;
						g_serial_rx_textBuff[g_serial_rx_charIndex] = '\0'; /* replace deleted char with null */
					}

					if(g_serial_rx_charIndex == 0)
					{
						g_serial_rx_receiving_msg = false;
					}
				}
				else
				{
					if(rx_char == ' ')
					{
						if(g_serial_rx_textBuff[g_serial_rx_charIndex - 1] == ':') // Meshtastic flag ": " detected
						{
							g_serial_rx_useMeshMode = true;
							g_serial_rx_invalidCommand = false;
							g_serial_rx_buff->fields[0][0] = '1';
							g_serial_rx_buff->fields[0][1] = '\0';
							/* Publish last so foreground sees a fully-populated message buffer. */
							g_serial_rx_buff->id = SB_MODE_MESH;
							serialbus_reset_rx_parser();
						}
						else if(g_serial_rx_invalidCommand && (g_serial_rx_field_index == 0))
						{
							/* Noise cannot become a valid command or Meshtastic prefix after a plain space. */
							rx_char = '\0';
							serialbus_reset_rx_parser();
						}
						else if((g_serial_rx_textBuff[g_serial_rx_charIndex - 1] == ' ') ||
						        ((g_serial_rx_field_index + 1) >= SERIALBUS_MAX_MSG_NUMBER_OF_FIELDS))
						{
							rx_char = '\0';
						}
						else
						{
							if(g_serial_rx_field_index > 0)
							{
								g_serial_rx_buff->fields[g_serial_rx_field_index - 1][g_serial_rx_field_len] = '\0';
							}

							g_serial_rx_field_index++;
							g_serial_rx_field_len = 0;
							g_serial_rx_charIndex = MIN(g_serial_rx_charIndex + 1, (SERIALBUS_MAX_MSG_LENGTH - 1));
						}
					}
					else if(g_serial_rx_field_index == 0) /* message ID received */
					{
						g_serial_rx_field_len++;

						if(g_serial_rx_field_len <= SERIALBUS_MAX_MSG_ID_LENGTH)
						{
							g_serial_rx_msg_ID = g_serial_rx_msg_ID * 10 + rx_char;
						}
						else
						{
							g_serial_rx_msg_ID = SB_MESSAGE_EMPTY;
							g_serial_rx_invalidCommand = true;

							if(g_serial_rx_field_len > SERIALBUS_MAX_MESHTASTIC_PREFIX_LENGTH)
							{
								/* Drop impossible noise quickly instead of waiting for a line terminator. */
								rx_char = '\0';
								serialbus_reset_rx_parser();
							}
						}

						if(g_serial_rx_buff)
						{
							g_serial_rx_charIndex = MIN(g_serial_rx_charIndex + 1, (SERIALBUS_MAX_MSG_LENGTH - 1));
						}
					}
					else if(g_serial_rx_field_len < (SERIALBUS_MAX_MSG_FIELD_LENGTH - 1))
					{
						g_serial_rx_buff->fields[g_serial_rx_field_index - 1][g_serial_rx_field_len++] = rx_char;
						g_serial_rx_buff->fields[g_serial_rx_field_index - 1][g_serial_rx_field_len] = '\0';
						g_serial_rx_charIndex = MIN(g_serial_rx_charIndex + 1, (SERIALBUS_MAX_MSG_LENGTH - 1));
					}
					else
					{
						rx_char = '\0';
						g_serial_rx_charIndex = MIN(g_serial_rx_charIndex + 1, (SERIALBUS_MAX_MSG_LENGTH - 1));
					}
				}
			}
			else
			{
				if(rx_char == 0x7F) /* Handle Backspace */
				{
					if(g_serial_rx_msg_ID <= 0)
					{
						rx_char = '\0';
					}

					g_serial_rx_msg_ID = 0;
				}
				else if(!isalnum(rx_char) && (rx_char != '?')) /* Handle Space and other non-alphanumeric characters */
				{
					if((rx_char == '@') && (g_serial_rx_charIndex == 0))
					{
						g_serial_rx_useMeshMode = false;
						g_serial_rx_invalidCommand = false;
						g_serial_rx_buff->fields[0][0] = '0';
						g_serial_rx_buff->fields[0][1] = '\0';
						/* Publish last so foreground sees a fully-populated message buffer. */
						g_serial_rx_buff->id = SB_MODE_MESH;
						serialbus_reset_rx_parser();
					}

					rx_char = '\0';
				}
				else /* start of new message */
				{
					uint8_t i;
					g_serial_rx_field_index = 0;
					g_serial_rx_msg_ID = rx_char;
					g_serial_rx_invalidCommand = false;

					/* Empty the field buffers */
					for(i = 0; i < SERIALBUS_MAX_MSG_NUMBER_OF_FIELDS; i++)
					{
						g_serial_rx_buff->fields[i][0] = '\0';
					}

					g_serial_rx_receiving_msg = true;
					g_serial_rx_charIndex++;
					g_serial_rx_field_len = 1;
				}
			}

			if(rx_char && !g_serial_rx_useMeshMode)
			{
				(void)sb_echo_char_isr(echo_char); /* Non-blocking ISR-safe echo enqueue */
			}

			serial_rx_idle_ticks_write_atomic(serialbus_rx_idle_reload_ticks());
		}
	}
}

/**

*/
ISR(USART1_DRE_vect)
{
	if(g_serialbus_usart_number == USART_1)
	{
		static SerialbusTxBuffer *buff = 0;
		static uint8_t charIndex = 0;

		if(!buff)
		{
			buff = nextFullSBTxBuffer();
		}

		{
			uint8_t echo_char;
			if(serialbus_echo_try_get_isr(&echo_char))
			{
				USART1.TXDATAL = echo_char;
				return;
			}
		}
		if(!buff)
		{
			serialbus_end_tx();
			return;
		}
		if((*buff)[charIndex])
		{
			/* Put data into buffer, sends the data */
			USART1.TXDATAL = (*buff)[charIndex++];
		}
		else
		{
			charIndex = 0;
			(*buff)[0] = '\0';
			buff = nextFullSBTxBuffer();
			if(!buff)
			{
				serialbus_end_tx();
			}
		}
	}
}

/**

*/
ISR(USART1_RXC_vect)
{
	uint8_t rx_char = USART1_get_data();

	if(g_serialbus_usart_number == USART_1)
	{
		serial_Rx(rx_char);
	}
}
