M48
; DRILL file {KiCad (6.0.4-0)} date Wednesday, June 21, 2023 at 09:10:14 PM
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-06-21T21:10:14-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.4-0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.500
%
G90
G05
T1
X115.28Y-63.46
T2
X51.855Y-71.95
X51.855Y-106.875
X128.055Y-71.95
X128.055Y-106.875
T0
M30
